### ISSUE TITLE
Fixing the Wrong Usages in the React App and Following the Best Practices

### ISSUE THREAD

**Issue by alpercakan** [bounswe/bounswe2019group8#191]
**Actions:**
1. Use setState instead of direct assignment to the state object. (#190)
2. Use a router library instead of the huge block of if-else (#192)
3. Send the API requests in the appropriate life-cycle methods instead of in the render method. (#193)
4. Using class components instead of function components (this one is just a personal suggestion for simplicity)

**Notes:**
For all of us, it is always helpful to look up some tutorials and best-practices before diving into the implementation. [the React official beginner's tutorial](https://reactjs.org/tutorial/tutorial.html) and the slightly longer [tutorial-docs](https://reactjs.org/docs/state-and-lifecycle.html) are really helpful.

**Deadline:** 30.10.2019 - 23.59

**Comment by furkanaydar** [comment]
Regarding the actions 1 and 4:
We can still use functional components instead of the class components, which will give us the opportunity to use the React hooks for the state management. See [React Hooks](https://tr.reactjs.org/docs/hooks-intro.html)

**Comment by alpercakan** [comment]
You are right about 4. I was going to write it in more detail in another issue, but let me just write it here: We need lifecycle methods in most components. While we can do that using hooks, I think for now we should just use the plain old class components in all cases since we are not particularly worried about performance etc. But as I said, that one is just a suggestion.

About 1: Currently, as shown in the examples of #190, we are modifying the state object directly, at various points, in a class component (`class App`). We just fix those.

**Comment by baris-zongur-2016400285** [comment]
Since all of your concerns about front-end is summarized here I think other issues seems unnecessary.

For part 1: Sorry about not using setState method for one or two places, we are aware of that it is the correct usage, parts you are seeing are currently under development.

For part 2: Please check (#192) 's comments so we can argue about that.

For part 3: A documentation about how to use your API would be helpful. If you already prepared one please response with appropriate link. 

For part 4: In cases where hook is needed, we are using functions, anywhere else we are using class component.  

Thank you for your concerns and useful links. If you have more please share with us. See you on saturday.

**Comment by alpercakan** [comment]
The API doc is at https://documenter.getpostman.com/view/8736871/SVzuZgBL?version=latest, as Sercan has previously shared. (for example, in our Wiki home page).

If you mean where the requests for the API should be sent; well, that is not about our API in particular. That is about consuming a RESTful API in a React application in general, and as I have stated in the related issue, as far as I remember, data population calls should be sent in the componentDidMount lifecycle method. (https://pusher.com/tutorials/consume-restful-api-react supports that. Many more examples and tutorials come up when searched "how to consume restful api in react" or "react lifecycyle api call").
