### ISSUE TITLE
Using a Router Library

### ISSUE THREAD

**Issue by alpercakan** [bounswe/bounswe2019group8#192]
**Actions:**
1. Use a router library instead of using an if-else block.

**Notes:**
1. Currently, there is a huge if-else block governing the routing in our App.jsx file. Instead, a router library, such as [react-router](https://www.npmjs.com/package/react-router) (which is, AFAIK, the most popular and is being used by millions of people) should be used.
2. The tutorial is here: https://reacttraining.com/react-router/web/guides/quick-start
The tutorial also includes examples of using the library for auth and permission based routing.

**Deadline:** 29.10.2019 - 23.59

**Comment by baris-zongur-2016400285** [comment]
Actually at first we were using router for rendering in same page but in implementation what it does is refreshing pages(visually) even while opening and closing the sign-up component. So for rendering of small components we decided not to use router and a big portion of the if-else block is about rendering components. We could use router for rendering different types of navbar and we are considering it but since decision of which component will be rendered comes from the state of the state variables, just using router will not reduce the if-else block. We are working on reducing the if else block and after that we can argue about changing some rendering to router instead of returning another component.
